issue-845-fix: True
mockname: "{{.InterfaceName}}Mock"
outpkg: "{{.PackageName}}mocks"
filename: "mock_{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}/{{.PackageName}}mocks"
inpackage: False
packages:
  github.com/dereulenspiegel/smolmailer/internal:
    config:
      recursive: True
      all: True
  github.com/dereulenspiegel/smolmailer/internal/queue:
    config:
      all: False
    interfaces:
      GenericQueue:
      GenericWorkQueue:
