issue-845-fix: True
mockname: "{{.InterfaceName}}Mock"
filename: "mock_{{.InterfaceName}}_test.go"
dir: "{{.InterfaceDir}}"
inpackage: True
packages:
  github.com/dereulenspiegel/smolmailer:
    # place your package-specific config here
    config:
    interfaces:
      # select the interfaces you want mocked
      GenericQueue:
      GenericWorkQueue:
      userService:
  github.com/dereulenspiegel/smolmailer/internal/config:
    interfaces:
      viperIf:
