name: Build Container Image
description: Build and push the container image
inputs:
  tag:
    description: Container image tag
    required: true
  latest-tag:
    description: Name of the latest tag
    required: true
    default: latest-dev
  registry-username:
    description: username for the registry
    required: true
  registry-password:
    description: password for the container registry
    required: true

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # zizmor: ignore[cache-poisoning]
    - name: GHCR Login
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
      with:
        registry: ghcr.io
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-password }}
    - name: Build and push
      uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/dereulenspiegel/smolmailer:${{ inputs.latest-tag }}, ghcr.io/dereulenspiegel/smolmailer:${{ inputs.tag }}
