// Code generated by mockery v2.53.5. DO NOT EDIT.

package backendmocks

import mock "github.com/stretchr/testify/mock"

// LoginAuthenticatorMock is an autogenerated mock type for the LoginAuthenticator type
type LoginAuthenticatorMock struct {
	mock.Mock
}

type LoginAuthenticatorMock_Expecter struct {
	mock *mock.Mock
}

func (_m *LoginAuthenticatorMock) EXPECT() *LoginAuthenticatorMock_Expecter {
	return &LoginAuthenticatorMock_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: username, password
func (_m *LoginAuthenticatorMock) Execute(username string, password string) error {
	ret := _m.Called(username, password)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(username, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LoginAuthenticatorMock_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type LoginAuthenticatorMock_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - username string
//   - password string
func (_e *LoginAuthenticatorMock_Expecter) Execute(username interface{}, password interface{}) *LoginAuthenticatorMock_Execute_Call {
	return &LoginAuthenticatorMock_Execute_Call{Call: _e.mock.On("Execute", username, password)}
}

func (_c *LoginAuthenticatorMock_Execute_Call) Run(run func(username string, password string)) *LoginAuthenticatorMock_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *LoginAuthenticatorMock_Execute_Call) Return(_a0 error) *LoginAuthenticatorMock_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LoginAuthenticatorMock_Execute_Call) RunAndReturn(run func(string, string) error) *LoginAuthenticatorMock_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewLoginAuthenticatorMock creates a new instance of LoginAuthenticatorMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoginAuthenticatorMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoginAuthenticatorMock {
	mock := &LoginAuthenticatorMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
