// Code generated by mockery v2.53.5. DO NOT EDIT.

package sendermocks

import (
	context "context"

	liteq "github.com/dereulenspiegel/liteq"
	mock "github.com/stretchr/testify/mock"
)

// JobQueueMock is an autogenerated mock type for the JobQueue type
type JobQueueMock[M interface{}] struct {
	mock.Mock
}

type JobQueueMock_Expecter[M interface{}] struct {
	mock *mock.Mock
}

func (_m *JobQueueMock[M]) EXPECT() *JobQueueMock_Expecter[M] {
	return &JobQueueMock_Expecter[M]{mock: &_m.Mock}
}

// Consume provides a mock function with given fields: _a0, _a1, _a2
func (_m *JobQueueMock[M]) Consume(_a0 context.Context, _a1 liteq.ConsumeFunc[M], _a2 ...liteq.ConsumeOpt) error {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, liteq.ConsumeFunc[M], ...liteq.ConsumeOpt) error); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// JobQueueMock_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type JobQueueMock_Consume_Call[M interface{}] struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 liteq.ConsumeFunc[M]
//   - _a2 ...liteq.ConsumeOpt
func (_e *JobQueueMock_Expecter[M]) Consume(_a0 interface{}, _a1 interface{}, _a2 ...interface{}) *JobQueueMock_Consume_Call[M] {
	return &JobQueueMock_Consume_Call[M]{Call: _e.mock.On("Consume",
		append([]interface{}{_a0, _a1}, _a2...)...)}
}

func (_c *JobQueueMock_Consume_Call[M]) Run(run func(_a0 context.Context, _a1 liteq.ConsumeFunc[M], _a2 ...liteq.ConsumeOpt)) *JobQueueMock_Consume_Call[M] {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]liteq.ConsumeOpt, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(liteq.ConsumeOpt)
			}
		}
		run(args[0].(context.Context), args[1].(liteq.ConsumeFunc[M]), variadicArgs...)
	})
	return _c
}

func (_c *JobQueueMock_Consume_Call[M]) Return(_a0 error) *JobQueueMock_Consume_Call[M] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *JobQueueMock_Consume_Call[M]) RunAndReturn(run func(context.Context, liteq.ConsumeFunc[M], ...liteq.ConsumeOpt) error) *JobQueueMock_Consume_Call[M] {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function with given fields: _a0, _a1, _a2
func (_m *JobQueueMock[M]) Put(_a0 context.Context, _a1 M, _a2 ...liteq.QueueOption) error {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, M, ...liteq.QueueOption) error); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// JobQueueMock_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type JobQueueMock_Put_Call[M interface{}] struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 M
//   - _a2 ...liteq.QueueOption
func (_e *JobQueueMock_Expecter[M]) Put(_a0 interface{}, _a1 interface{}, _a2 ...interface{}) *JobQueueMock_Put_Call[M] {
	return &JobQueueMock_Put_Call[M]{Call: _e.mock.On("Put",
		append([]interface{}{_a0, _a1}, _a2...)...)}
}

func (_c *JobQueueMock_Put_Call[M]) Run(run func(_a0 context.Context, _a1 M, _a2 ...liteq.QueueOption)) *JobQueueMock_Put_Call[M] {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]liteq.QueueOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(liteq.QueueOption)
			}
		}
		run(args[0].(context.Context), args[1].(M), variadicArgs...)
	})
	return _c
}

func (_c *JobQueueMock_Put_Call[M]) Return(_a0 error) *JobQueueMock_Put_Call[M] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *JobQueueMock_Put_Call[M]) RunAndReturn(run func(context.Context, M, ...liteq.QueueOption) error) *JobQueueMock_Put_Call[M] {
	_c.Call.Return(run)
	return _c
}

// NewJobQueueMock creates a new instance of JobQueueMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJobQueueMock[M interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *JobQueueMock[M] {
	mock := &JobQueueMock[M]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
