// Code generated by mockery v2.53.3. DO NOT EDIT.

package sendermocks

import (
	sender "github.com/dereulenspiegel/smolmailer/internal/sender"
	mock "github.com/stretchr/testify/mock"
)

// ProcessingOptMock is an autogenerated mock type for the ProcessingOpt type
type ProcessingOptMock struct {
	mock.Mock
}

type ProcessingOptMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ProcessingOptMock) EXPECT() *ProcessingOptMock_Expecter {
	return &ProcessingOptMock_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *ProcessingOptMock) Execute(_a0 *sender.PreprocessorHandler) {
	_m.Called(_a0)
}

// ProcessingOptMock_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ProcessingOptMock_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *sender.PreprocessorHandler
func (_e *ProcessingOptMock_Expecter) Execute(_a0 interface{}) *ProcessingOptMock_Execute_Call {
	return &ProcessingOptMock_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *ProcessingOptMock_Execute_Call) Run(run func(_a0 *sender.PreprocessorHandler)) *ProcessingOptMock_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*sender.PreprocessorHandler))
	})
	return _c
}

func (_c *ProcessingOptMock_Execute_Call) Return() *ProcessingOptMock_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *ProcessingOptMock_Execute_Call) RunAndReturn(run func(*sender.PreprocessorHandler)) *ProcessingOptMock_Execute_Call {
	_c.Run(run)
	return _c
}

// NewProcessingOptMock creates a new instance of ProcessingOptMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProcessingOptMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProcessingOptMock {
	mock := &ProcessingOptMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
