// Code generated by mockery v2.53.5. DO NOT EDIT.

package sendermocks

import (
	queue "github.com/dereulenspiegel/smolmailer/internal/queue"
	mock "github.com/stretchr/testify/mock"
)

// PreSendProcessorMock is an autogenerated mock type for the PreSendProcessor type
type PreSendProcessorMock struct {
	mock.Mock
}

type PreSendProcessorMock_Expecter struct {
	mock *mock.Mock
}

func (_m *PreSendProcessorMock) EXPECT() *PreSendProcessorMock_Expecter {
	return &PreSendProcessorMock_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *PreSendProcessorMock) Execute(_a0 *queue.QueuedMessage) (*queue.QueuedMessage, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *queue.QueuedMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(*queue.QueuedMessage) (*queue.QueuedMessage, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*queue.QueuedMessage) *queue.QueuedMessage); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*queue.QueuedMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(*queue.QueuedMessage) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PreSendProcessorMock_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type PreSendProcessorMock_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *queue.QueuedMessage
func (_e *PreSendProcessorMock_Expecter) Execute(_a0 interface{}) *PreSendProcessorMock_Execute_Call {
	return &PreSendProcessorMock_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *PreSendProcessorMock_Execute_Call) Run(run func(_a0 *queue.QueuedMessage)) *PreSendProcessorMock_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*queue.QueuedMessage))
	})
	return _c
}

func (_c *PreSendProcessorMock_Execute_Call) Return(_a0 *queue.QueuedMessage, _a1 error) *PreSendProcessorMock_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PreSendProcessorMock_Execute_Call) RunAndReturn(run func(*queue.QueuedMessage) (*queue.QueuedMessage, error)) *PreSendProcessorMock_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewPreSendProcessorMock creates a new instance of PreSendProcessorMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPreSendProcessorMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *PreSendProcessorMock {
	mock := &PreSendProcessorMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
